export enum CategoryTypes {
  DRINKING_FOUNTAIN = 'DRINKING_FOUNTAIN',
  WATER_REFILL_POINT = 'WATER_REFILL_POINT',
  PAPER = 'PAPER',
  PLASTIC = 'PLASTIC',
  METAL = 'METAL',
  GREEN_WASTE = 'GREEN_WASTE',
  COLORFUL_GLASS = 'COLORFUL_GLASS',
  TRANSPARENT_GLASS = 'TRANSPARENT_GLASS'
}
