export enum OperationType {
  RECOMMENDATION = 'RECOMMENDATION',
  MODIFY_REQUEST = 'MODIFY_REQUEST',
  DELETE_REQUEST = 'DELETE_REQUEST',
  MODIFICATION = 'MODIFICATION',
  DELETION = 'DELETION',
  ACCEPTANCE = 'ACCEPTANCE',
  DENIAL = 'DENIAL'
}
