export enum PlaceCategory {
  ZERO_WASTE_SHOP = 'ZERO_WASTE_SHOP',
  WATER_REFILL = 'WATER_REFILL',
  COMMUNITY_COMPOST = 'COMMUNITY_COMPOST',
  RECYCLE_BIN = 'RECYCLE_BIN',
  HAZARDOUS_WASTE_DISPOSAL = 'HAZARDOUS_WASTE_DISPOSAL',
  OTHER = 'OTHER'
}
